import type { Config } from "tailwindcss"

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        secondary: "#b9c8de",
        surface: "#0b1326",
        primary: "#c3f5ff",
        "surface-container-lowest": "#060e20",
        "surface-container": "#171f33",
        "on-primary-container": "#00626e",
        "on-secondary-fixed-variant": "#39485a",
        "on-secondary-container": "#a7b6cc",
        "on-error-container": "#ffdad6",
        "surface-container-highest": "#2d3449",
        "on-primary-fixed-variant": "#004f58",
        "secondary-container": "#39485a",
        tertiary: "#e6edff",
        "on-primary-fixed": "#001f24",
        "surface-dim": "#0b1326",
        outline: "#849396",
        "surface-tint": "#00daf3",
        "on-secondary": "#233143",
        "tertiary-fixed": "#d8e3fb",
        "on-tertiary-container": "#4f5a6e",
        "on-background": "#dae2fd",
        "inverse-on-surface": "#283044",
        "inverse-surface": "#dae2fd",
        "on-surface-variant": "#bac9cc",
        "secondary-fixed-dim": "#b9c8de",
        "secondary-fixed": "#d4e4fa",
        "surface-variant": "#2d3449",
        "error-container": "#93000a",
        error: "#ffb4ab",
        "primary-fixed": "#9cf0ff",
        "surface-container-high": "#222a3d",
        "on-error": "#690005",
        "primary-container": "#00e5ff",
        "on-tertiary-fixed-variant": "#3c475a",
        "surface-container-low": "#131b2e",
        "on-tertiary-fixed": "#111c2d",
        "inverse-primary": "#006875",
        "outline-variant": "#3b494c",
        "on-tertiary": "#263143",
        "on-secondary-fixed": "#0d1c2d",
        "surface-bright": "#31394d",
        "on-primary": "#00363d",
        "on-surface": "#dae2fd",
        "primary-fixed-dim": "#00daf3",
        "tertiary-fixed-dim": "#bcc7de",
        "tertiary-container": "#c6d1e9",
        background: "#0b1326",
      },
      fontFamily: {
        sans: ["var(--font-inter)"],
        mono: ["var(--font-space-grotesk)"],
      },
      fontSize: {
        "code-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      spacing: {
        "container-max": "1200px",
        margin: "32px",
        "stack-lg": "64px",
        unit: "8px",
        "stack-sm": "16px",
        gutter: "24px",
        "stack-md": "32px",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
}

export default config
