"use client";

import * as React from "react";
import {
  ThemeProvider as NextThemesProvider,
  type ThemeProviderProps,
} from "next-themes";

// Suppress Framer Motion oklab color warning - oklab is generated by Tailwind v4 but Motion doesn't support it
if (typeof window !== "undefined") {
  const originalWarn = console.warn;
  console.warn = function (...args: any[]) {
    const message = args[0]?.toString?.() || "";
    if (
      message.includes("oklab") &&
      message.includes("not an animatable color")
    ) {
      return;
    }
    originalWarn.apply(console, args);
  };
}

export function ThemeProvider({ children, ...props }: ThemeProviderProps) {
  return <NextThemesProvider {...props}>{children}</NextThemesProvider>;
}
